CREATE TABLE IF NOT EXISTS `db_con_sql` (
    `Database_configuration` VARCHAR(54) CHARACTER SET utf8,
    `Column_2` VARCHAR(16) CHARACTER SET utf8,
    `Column_3` VARCHAR(12) CHARACTER SET utf8
);
INSERT INTO `db_con_sql` VALUES ('$servername = "localhost";',NULL,NULL),
	('$username = "your_username";',NULL,NULL),
	('$password = "your_password";',NULL,NULL),
	(NULL,NULL,NULL),
	('// Connect to MySQL server',NULL,NULL),
	('$conn = new mysqli($servername',' $username',' $password);'),
	(NULL,NULL,NULL),
	('// Check connection',NULL,NULL),
	('if ($conn->connect_error) {',NULL,NULL),
	('    die("Connection failed: " . $conn->connect_error);',NULL,NULL),
	('}',NULL,NULL),
	(NULL,NULL,NULL),
	('// Create database',NULL,NULL),
	('$sql = "CREATE DATABASE my_database";',NULL,NULL),
	('if ($conn->query($sql) === TRUE) {',NULL,NULL),
	('    echo "Database created successfully";',NULL,NULL),
	('} else {',NULL,NULL),
	('    echo "Error creating database: " . $conn->error;',NULL,NULL),
	('}',NULL,NULL),
	(NULL,NULL,NULL),
	('// Select database',NULL,NULL),
	('mysqli_select_db($conn',' "my_database");',NULL),
	(NULL,NULL,NULL),
	('// Create table',NULL,NULL),
	('$sql = "CREATE TABLE users (',NULL,NULL),
	('        id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY',NULL,NULL),
	('        username VARCHAR(30) NOT NULL',NULL,NULL),
	('        email VARCHAR(50) NOT NULL',NULL,NULL),
	('        password VARCHAR(255) NOT NULL',NULL,NULL),
	('        age INT(3)',NULL,NULL),
	('        dob DATE',NULL,NULL),
	('        contact VARCHAR(20)',NULL,NULL),
	('    )";',NULL,NULL),
	('if ($conn->query($sql) === TRUE) {',NULL,NULL),
	('    echo "Table created successfully";',NULL,NULL),
	('} else {',NULL,NULL),
	('    echo "Error creating table: " . $conn->error;',NULL,NULL),
	('}',NULL,NULL),
	(NULL,NULL,NULL),
	('// Close connection',NULL,NULL),
	('$conn->close();',NULL,NULL);
